-------------------------------------------------------------------
---------------------PGBANK ADDED COLUMN---------------------------
-------------------------------------------------------------------


ALTER TABLE `acquirer_uat_test`.`PG_BANK`
ADD COLUMN `BANK_CODE` VARCHAR(50) NULL AFTER `SETTL_ACCOUNT_NUMBER`,
ADD COLUMN `EXTENSION` VARCHAR(5) NULL AFTER `BANK_CODE`,
ADD COLUMN `CONTACT_PERSON_CELL` VARCHAR(50) NULL AFTER `EXTENSION`,
ADD COLUMN `CONTACT_PERSON_NAME` VARCHAR(50) NULL AFTER `CONTACT_PERSON_CELL`,
ADD COLUMN `CONTACT_PERSON_FAX` VARCHAR(50) NULL AFTER `CONTACT_PERSON_NAME`,
ADD COLUMN `CONTACT_PERSON_EMAIL` VARCHAR(50) NULL AFTER `CONTACT_PERSON_FAX`,
ADD COLUMN `CONTACT_PERSON_PHONE` VARCHAR(50) NULL AFTER `CONTACT_PERSON_EMAIL`;

COMMIT;