package com.chatak.pg.enums;

public enum TransactionCodeEnum {
	//Admin Codes
	LOADCARD,
	AGENTLOADCARD,
	LOADCARDFEE,
	LOADCARDREVERSAL,
	AGENTLOADCARDREVERSAL,
	FEEREVERSAL,
	UPLOADFUNDS,
	MANUAL_CREDIT,
	MANUAL_DEBIT,
	TRANSFER_FUNDS_TO_OWN_ACCOUNT,
	TRANSFER_FUNDS_TO_OTHER_ACCOUNT,
	SEND_FUNDS_TO_BANK_ACCOUNT_EFT,
	SEND_FUNDS_BY_CHEQUE_TO_BANK,
	LOAD_FUNDS_FROM_BANK_ACCOUNT,
	
	//N/w transaction code
	POS_PURCHASE,
	ATM_WITHDRAW,
	POS_PURCHASE_WITH_CASHBACK,
	POS_REFUND,
	ATM_DEPOSIT,
	BALANCE_INQUIRY,
	POS_ECOM_PURCHASE,
	POS_ECOM_CREDIT,
	REVERSAL,
	ATM_TRANSFER_BW_ACCOUNTS,
	POS_TRANSFER_BW_ACCOUNTS,
	AUTH_COMPLETION_DEBIT,
	AUTH_COMPLETION_CREDIT,
	ACQUIRER_FEE,
	ISSUER_FEE;
}